-- V10__Add_Account_Totp_Credentials.sql

-- 1. Create account_totp_credentials table
CREATE TABLE dbo.account_totp_credentials (
    id BIGINT IDENTITY(1,1) PRIMARY KEY,
    account_id BIGINT NOT NULL,
    encrypted_secret VARBINARY(MAX) NOT NULL,
    encryption_iv VARBINARY(32) NOT NULL,
    encryption_key_version VARCHAR(30) NULL,
    enabled BIT NOT NULL DEFAULT 0,
    enrollment_id UNIQUEIDENTIFIER NULL,
    enrollment_expires_at DATETIME2 NULL,
    verified_at DATETIME2 NULL,
    last_accepted_time_step BIGINT NULL,
    failed_attempts INT NOT NULL DEFAULT 0,
    locked_until DATETIME2 NULL,
    created_at DATETIME2 NOT NULL,
    updated_at DATETIME2 NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT FK_account_totp_credentials_account
        FOREIGN KEY (account_id)
        REFERENCES dbo.accounts(id),

    CONSTRAINT UQ_account_totp_credentials_account
        UNIQUE (account_id)
);

-- 2. Update audit_logs check constraint
DECLARE @ConstraintName NVARCHAR(200);

SELECT @ConstraintName = cc.name
FROM sys.check_constraints cc
JOIN sys.columns c
    ON c.object_id = cc.parent_object_id
WHERE cc.parent_object_id = OBJECT_ID('dbo.audit_logs')
  AND c.name = 'action'
  AND cc.definition LIKE '%action%';

IF @ConstraintName IS NOT NULL
BEGIN
    EXEC(
        'ALTER TABLE dbo.audit_logs DROP CONSTRAINT ['
        + @ConstraintName
        + ']'
    );
END;

ALTER TABLE dbo.audit_logs
ADD CONSTRAINT CK_audit_logs_action
CHECK (
    action IN (
        'CREATE_PROJECT',
        'UPLOAD_DOCUMENT',
        'MANUAL_INPUT',
        'SUBMIT_CANDIDATE',
        'APPROVE_CANDIDATE',
        'REJECT_CANDIDATE',
        'CORRECT_CANDIDATE',
        'CREATE_PROFILE',
        'UPDATE_PROFILE',
        'CREATE_GRAPH_NODE',
        'CREATE_RELATIONSHIP',
        'LOGIN',
        'LOGOUT',
        'REFRESH_TOKEN',
        'USER_CREATED',
        'USER_UPDATED',
        'USER_STATUS_CHANGED',
        'USER_ROLES_UPDATED',
        'COMPANY_PROFILE_UPDATED',
        'COMPANY_PROFILE_ARCHIVED',
        'DOCUMENT_HIDDEN',
        'DOCUMENT_DELETED',
        'REPORT_EXPORTED',
        'AUDIT_LOG_EXPORTED',
        'PROJECT_TASK_CREATED',
        'PROJECT_TASK_UPDATED',
        'PROJECT_TASK_STATUS_CHANGED',
        'PROJECT_TASK_ASSIGNED',
        'NOTIFICATION_SENT',
        'NOTIFICATION_READ',
        'NOTIFICATION_DELETED',
        'EXTERNAL_DATA_FETCHED',
        'EXTERNAL_DATA_ANALYZED',
        'PROJECT_TASK_SUBMITTED',
        'PROJECT_TASK_SUBMISSION_APPROVED',
        'PROJECT_TASK_SUBMISSION_REJECTED',
        'PROJECT_TASK_REVISION_REQUESTED',
        'PROFILE_UPDATE_PROPOSAL_CREATED',
        'PROFILE_UPDATE_PROPOSAL_APPROVED',
        'COMPANY_PROFILE_VERSION_CREATED',
        'PROFILE_UPDATE_PROPOSAL_APPLIED',
        'EXTRACTION_MERGED_TO_CANDIDATE',
        'EXTRACTION_MERGED_TO_PROFILE_PROPOSAL',
        'FIELD_EVIDENCE_CONFLICT_DETECTED',
        'PROJECT_STATUS_CHANGED',
        'PROJECT_COMPLETED',
        'PROJECT_CANCELLED',
        'PROJECT_ARCHIVED',
        'COMPANY_MEMBER_RESEARCH_DRAFT_CREATED',
        'COMPANY_MEMBER_RESEARCH_DRAFT_UPDATED',
        'COMPANY_MEMBER_RESEARCH_SUBMITTED',
        'COMPANY_MEMBER_RESEARCH_APPROVED',
        'COMPANY_MEMBER_RESEARCH_REJECTED',
        'COMPANY_PROFILE_MEMBERS_UPDATED',
        'ROLE_EVALUATION_DRAFT_CREATED',
        'ROLE_EVALUATION_CRITERION_UPDATED',
        'ROLE_EVALUATION_EVIDENCE_ADDED',
        'ROLE_EVALUATION_SUGGESTION_GENERATED',
        'ROLE_EVALUATION_SUGGESTION_ACCEPTED',
        'ROLE_EVALUATION_SUBMITTED',
        'ROLE_EVALUATION_REVISION_REQUESTED',
        'ROLE_EVALUATION_REJECTED',
        'ROLE_EVALUATION_APPROVAL_STARTED',
        'ROLE_EVALUATION_APPROVAL_FAILED',
        'ROLE_EVALUATION_APPROVED',
        'CANONICAL_SCORE_SNAPSHOT_CREATED',
        'PARTNER_CONTRACT_CREATED',
        'PARTNER_CONTRACT_UPDATED',
        'PARTNER_CONTRACT_SUBMITTED',
        'PARTNER_CONTRACT_APPROVED',
        'PARTNER_CONTRACT_CHANGES_REQUESTED',
        'PARTNER_CONTRACT_REVISION_STARTED',
        'PARTNER_CONTRACT_LIFECYCLE_CHANGED',
        'PARTNER_CONTRACT_EXTRACTION_STARTED',
        'PARTNER_CONTRACT_EXTRACTION_COMPLETED',
        'PARTNER_CONTRACT_EXTRACTION_FAILED',
        'PARTNER_CONTRACT_EXTRACTION_FIELD_REVIEWED',
        'PARTNER_CONTRACT_EXTRACTION_CLAUSE_REVIEWED',
        'PARTNER_CONTRACT_EXTRACTION_APPLIED',
        'PARTNER_CONTRACT_EXTRACTION_REGENERATED',
        'PARTNER_CONTRACT_CLAUSES_APPROVED',
        'PARTNER_CONTRACT_APPROVAL_SYNC_FAILED',
        'PARTNER_CONTRACT_APPROVAL_SYNC_COMPLETED',
        'ROLE_METRIC_CREATED',
        'ROLE_METRIC_UPDATED',
        'ROLE_METRIC_EVIDENCE_ATTACHED',
        'ROLE_METRIC_EVIDENCE_UPDATED',
        'ROLE_METRIC_EVIDENCE_DELETED',
        'ROLE_METRIC_SUBMITTED',
        'ROLE_METRIC_CHANGES_REQUESTED',
        'ROLE_METRIC_REJECTED',
        'ROLE_METRIC_APPROVED',
        'ROLE_METRIC_REOPENED',
        'ROLE_METRIC_REVISION_CREATED',
        'PARTNER_EVALUATION_SUGGESTION_GENERATED',
        'PARTNER_EVALUATION_SUGGESTION_ACCEPTED',
        'PARTNER_EVALUATION_SUGGESTION_EDITED',
        'PARTNER_EVALUATION_SUGGESTION_REJECTED',
        'PARTNER_EVALUATION_SUGGESTION_STALE',
        'PARTNER_EVALUATION_READINESS_EVALUATED',
        'PARTNER_EVALUATION_SUBMITTED',
        'PARTNER_EVALUATION_APPROVED',
        'PARTNER_EVALUATION_REVISION_REQUESTED',
        'PARTNER_EVALUATION_APPROVAL_CONFLICT',
        'PARTNER_EVALUATION_OUTBOX_PROCESSED',
        'PARTNER_EVALUATION_OUTBOX_FAILED',
        'COMPANY_NEWS_DRAFT_CREATED',
        'COMPANY_NEWS_DRAFT_UPDATED',
        'COMPANY_NEWS_DRAFT_DELETED',
        'COMPANY_NEWS_RESEARCH_SUBMITTED',
        'COMPANY_NEWS_RESEARCH_APPROVED',
        'COMPANY_NEWS_RESEARCH_REJECTED',
        'CONFIDENTIAL_NEWS_ACCESS_REQUESTED',
        'CONFIDENTIAL_NEWS_OTP_SENT',
        'CONFIDENTIAL_NEWS_OTP_VERIFIED',
        'CONFIDENTIAL_NEWS_ACCESS_DENIED',
        'CONFIDENTIAL_NEWS_ARTICLE_VIEWED',
        -- NEW ACTIONS FOR TOTP
        'TOTP_ENROLLMENT_STARTED',
        'TOTP_ENROLLMENT_COMPLETED',
        'TOTP_ENROLLMENT_FAILED',
        'TOTP_STEP_UP_SUCCEEDED',
        'TOTP_STEP_UP_FAILED',
        'TOTP_CREDENTIAL_RESET',
        'INTERNAL_NEWS_ACCESS_GRANTED',
        'INTERNAL_NEWS_ACCESS_DENIED'
    )
);
