package com.apms.domain.score.enums;

public enum ApprovedSourceType {
    ROLE_METRIC_VERSION,
    ROLE_METRIC_EVIDENCE_VERSION,
    PARTNER_CONTRACT_VERSION,
    PARTNER_CONTRACT_CLAUSE_VERSION,
    COMPANY_PROFILE_VERSION,
    RAW_DOCUMENT_SEGMENT,
    EXTERNAL,
    MANUAL_NOTE
}
