package com.apms.domain.score.enums;

public enum RoleEvaluationOutboxEventType {
    PARTNER_EVALUATION_SUBMITTED,
    PARTNER_EVALUATION_APPROVED,
    PARTNER_EVALUATION_REVISION_REQUESTED,
    POTENTIAL_PARTNER_EVALUATION_SUBMITTED,
    POTENTIAL_PARTNER_EVALUATION_APPROVED,
    POTENTIAL_PARTNER_EVALUATION_REVISION_REQUESTED,
    CUSTOMER_EVALUATION_SUBMITTED,
    CUSTOMER_EVALUATION_APPROVED,
    CUSTOMER_EVALUATION_REVISION_REQUESTED
}
