package com.apms.domain.candidate;

import com.apms.common.enums.CandidateStatus;
import com.apms.common.enums.RelationshipType;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.LocalDateTime;

/**
 * MongoDB document representing a draft or in-review company profile candidate.
 * Contains flexible AI-extracted data and embedded review workflow.
 *
 * Collection: company_candidates
 */
@Document(collection = "company_candidates")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class CompanyCandidate {

    @Id
    private String id;

    @Indexed
    private String projectId; // References SQL projects.id

    @Indexed
    private String importJobId; // References SQL import_jobs.id

    private String rawDocumentId; // References Mongo raw_documents.id

    /**
     * For projects extracting multiple companies, this keeps the ordering.
     */
    private Integer candidateOrder;

    /**
     * Incremented every time a candidate is CORRECTED.
     */
    @Builder.Default
    private Integer revisionNumber = 1;

    @Indexed
    private CandidateStatus status;

    /**
     * Temporary suggestion generated by AI.
     */
    private RelationshipType suggestedRelationshipType;
    
    private Double relationshipConfidenceScore;

    /**
     * Overridden by BD Manager during approval.
     */
    private RelationshipType relationshipTypeOverride;

    // ─────────────────────────────────────────────────────────────
    // Flexible Data Embedded Documents
    // ─────────────────────────────────────────────────────────────

    private Identity identity;
    private Business business;
    private CompanySize companySize;
    private Contact contact;
    private Insights insights;

    // ─────────────────────────────────────────────────────────────
    // Internal Workflow Embedded Documents
    // ─────────────────────────────────────────────────────────────

    private Validation validation;
    private Normalization normalization;
    private Deduplication deduplication;
    private ExtractionSource extractionSource;
    private Review review;
    private ScorePreview scorePreview;
    private AiMetadata aiMetadata;
    private Metadata metadata;

    // ─────────────────────────────────────────────────────────────
    // Nested Classes
    // ─────────────────────────────────────────────────────────────

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class Identity {
        private String name;
        private String registrationNumber;
        private String taxId;
        private String legalForm;
        private String foundedYear;
    }

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class Business {
        private String industry;
        private String subIndustry;
        private String description;
        private String coreProducts;
        private String marketPosition;
    }

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class CompanySize {
        private String employeeCountRange;
        private String estimatedRevenueRange;
        private String physicalLocationsCount;
    }

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class Contact {
        private String website;
        private String primaryEmail;
        private String primaryPhone;
        private String headquartersAddress;
        private String keyExecutives;
    }

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class Insights {
        private String strengths;
        private String weaknesses;
        private String opportunities;
        private String threats;
        private String strategicValue;
    }

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class Validation {
        private Boolean isComplete;
        private String missingCriticalFields;
        private String dataQualityScore;
    }

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class Normalization {
        private String normalizedName;
        private String normalizedIndustry;
    }

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class Deduplication {
        private String existingProfileIdMatch;
        private Double similarityScore;
    }

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class ExtractionSource {
        private String originFileName;
        private String extractionMethod; // e.g., "SPRING_AI", "MANUAL"
    }

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class Review {
        private String rejectionReason;
        private String reviewedBy; // userId
        private LocalDateTime reviewedAt;
    }

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class ScorePreview {
        private Integer estimatedTotalScore;
        private String scoreFactorsSummary;
    }

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class AiMetadata {
        private String promptVersion;
        private String modelUsed;
        private String rawResponseReference;
    }

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class Metadata {
        private String createdBy;
        private LocalDateTime createdAt;
        private String lastModifiedBy;
        private LocalDateTime updatedAt;
    }
}
