package com.apms.domain.candidate;

import com.apms.common.enums.CandidateStatus;
import com.apms.common.enums.RelationshipType;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.LocalDateTime;

/**
 * MongoDB document representing a draft or in-review company profile candidate.
 * Contains flexible AI-extracted data and embedded review workflow.
 *
 * Collection: company_candidates
 */
@Document(collection = "company_candidates")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class CompanyCandidate {

    @Id
    private String id;

    @Indexed
    private String projectId; // References SQL projects.id

    @Indexed
    private String importJobId; // References SQL import_jobs.id

    private String rawDocumentId; // References Mongo raw_documents.id

    @Indexed
    private Long taskId; // References SQL project_tasks.id

    private java.util.List<String> extractionIds; // References Mongo ai_extraction_caches.id

    private java.util.List<String> sourceDocumentIds; // Source raw doc IDs across all extractions

    /**
     * For projects extracting multiple companies, this keeps the ordering.
     */
    private Integer candidateOrder;

    /**
     * Incremented every time a candidate is CORRECTED.
     */
    @Builder.Default
    private Integer revisionNumber = 1;

    @Indexed
    private CandidateStatus status;

    /**
     * Temporary suggestion generated by AI.
     */
    private RelationshipType suggestedRelationshipType;
    
    private Double relationshipConfidenceScore;

    /**
     * Overridden by BD Manager during approval.
     */
    private RelationshipType relationshipTypeOverride;

    private RelationshipSuggestion relationshipSuggestion;
    private Lifecycle lifecycle;

    // ─────────────────────────────────────────────────────────────
    // Flexible Data Embedded Documents
    // ─────────────────────────────────────────────────────────────

    private Identity identity;
    private Business business;
    private CompanySize companySize;
    private Contact contact;
    private Insights insights;

    private com.apms.domain.company.model.FinancialInfo financial;
    private com.apms.domain.company.model.MarketInfo market;
    private com.apms.domain.company.model.InnovationInfo innovation;
    private com.apms.domain.company.model.RiskInfo risk;
    private com.apms.domain.company.model.ComplianceInfo compliance;

    // ─────────────────────────────────────────────────────────────
    // Internal Workflow Embedded Documents
    // ─────────────────────────────────────────────────────────────

    private Validation validation;
    private Normalization normalization;
    private Deduplication deduplication;
    private ExtractionSource extractionSource;
    private Review review;
    private ScorePreview scorePreview;
    private AiMetadata aiMetadata;
    private Metadata metadata;

    // ─────────────────────────────────────────────────────────────
    // Nested Classes
    // ─────────────────────────────────────────────────────────────

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class Identity {
        private String legalName;
        private String tradeName;
        private String taxCode;
        private String registrationNumber;
    }

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class Business {
        private java.util.List<String> industries;
        private String businessModel;
        private java.util.List<Product> products;
        private java.util.List<String> markets;
        private java.util.List<String> targetCustomers;
    }

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class Product {
        private String name;
        private String category;
        private String description;
    }

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class CompanySize {
        private String employeeTier;
        private Integer employeeCount;
        private String revenueTier;
    }

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class Contact {
        private String website;
        private java.util.List<String> emails;
        private java.util.List<String> phones;
        private java.util.List<Address> addresses;
    }

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class Address {
        private String type;
        private String fullAddress;
        private String city;
        private String country;
    }

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class Insights {
        private java.util.List<String> strengths;
        private java.util.List<String> weaknesses;
        private java.util.List<String> opportunities;
        private java.util.List<String> threats;
    }

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class RelationshipSuggestion {
        private RelationshipType suggestedType;
        private Double confidence;
        private java.util.List<AlternativeRelationship> alternatives;
        private java.util.List<String> reasoning;
    }

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class AlternativeRelationship {
        private RelationshipType type;
        private Double confidence;
    }

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class Lifecycle {
        private CandidateStatus status;
        private String convertedCompanyProfileId;
    }

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class Validation {
        private Boolean isComplete;
        private String missingCriticalFields;
        private String dataQualityScore;
    }

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class Normalization {
        private String normalizedName;
        private String normalizedIndustry;
    }

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class Deduplication {
        private String existingProfileIdMatch;
        private Double similarityScore;
    }

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class ExtractionSource {
        private String originFileName;
        private String extractionMethod; // e.g., "SPRING_AI", "MANUAL"
    }

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class Review {
        private String rejectionReason;
        private String reviewedBy; // userId
        private LocalDateTime reviewedAt;
    }

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class ScorePreview {
        private Integer estimatedTotalScore;
        private String scoreFactorsSummary;
    }

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class AiMetadata {
        private String promptVersion;
        private String modelUsed;
        private String rawResponseReference;
    }

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class Metadata {
        private String createdBy;
        private LocalDateTime createdAt;
        private String lastModifiedBy;
        private LocalDateTime updatedAt;
    }
}
