package com.apms.domain.ai.dto;

import lombok.Builder;
import lombok.Data;

@Data
@Builder
public class AiExtractionResult {

    private Long importJobId;
    private String rawDocumentId;

    /**
     * The structured data extracted from the document.
     */
    private ExtractedCompanyData extractedData;

    /**
     * The raw output generated by the AI (useful for debugging and audit).
     */
    private String rawAiOutput;
}
