spring.application.name=apms-backend

server.port=${PORT}

spring.profiles.default=dev

# JWT
jwt.expirationMs=${JWT_EXPIRATION_MS}

# AI Provider
app.ai.provider=${AI_PROVIDER}
app.ai.gemini.model=${GEMINI_MODEL}

# Owner Organization
apms.owner.company-profile-id=${APMS_OWNER_COMPANY_PROFILE_ID}

# JPA
spring.jpa.open-in-view=false