# =========================
# SQL Server
# =========================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:validate}
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false


# =========================
# MongoDB
# =========================
spring.data.mongodb.uri=${MONGO_URI}


# =========================
# Neo4j
# =========================
spring.neo4j.uri=${NEO4J_URI}
spring.neo4j.authentication.username=${NEO4J_USERNAME}
spring.neo4j.authentication.password=${NEO4J_PASSWORD}


# =========================
# JWT
# =========================
jwt.secret=${JWT_SECRET}


# =========================
# File Upload
# =========================
app.storage.upload-dir=${UPLOAD_DIR}


# =========================
# AI
# =========================

spring.ai.openai.api-key=${OPENAI_API_KEY:dummy-key}

app.ai.gemini.api-key=${GEMINI_API_KEY}


# =========================
# Reverse Proxy / Railway
# =========================
server.forward-headers-strategy=framework