package com.apms.common.enums;

public enum AuditAction {
    CREATE_PROJECT,
    UPLOAD_DOCUMENT,
    MANUAL_INPUT,
    SUBMIT_CANDIDATE,
    APPROVE_CANDIDATE,
    REJECT_CANDIDATE,
    CORRECT_CANDIDATE,
    CREATE_PROFILE,
    UPDATE_PROFILE,
    CREATE_GRAPH_NODE,
    CREATE_RELATIONSHIP,
    LOGIN,
    LOGOUT,
    REFRESH_TOKEN
}
