package com.apms.common.enums;

public enum AuditAction {
    CREATE_PROJECT,
    UPLOAD_DOCUMENT,
    MANUAL_INPUT,
    SUBMIT_CANDIDATE,
    APPROVE_CANDIDATE,
    REJECT_CANDIDATE,
    CORRECT_CANDIDATE,
    CREATE_PROFILE,
    UPDATE_PROFILE,
    CREATE_GRAPH_NODE,
    CREATE_RELATIONSHIP,
    LOGIN,
    LOGOUT,
    REFRESH_TOKEN,
    USER_CREATED,
    USER_UPDATED,
    USER_STATUS_CHANGED,
    USER_ROLES_UPDATED,
    COMPANY_PROFILE_UPDATED,
    COMPANY_PROFILE_ARCHIVED,
    DOCUMENT_HIDDEN,
    DOCUMENT_DELETED,
    REPORT_EXPORTED,
    AUDIT_LOG_EXPORTED
}
