package com.apms.common.enums;

public enum TaskType {
    @Deprecated
    DOCUMENT_COLLECTION,
    COMPANY_DATA_PREPARATION,
    COMPANY_MEMBER_RESEARCH,
    PARTNER_CONTRACT_COLLECTION,
    ROLE_EVALUATION,
    COMPANY_NEWS_RESEARCH,
    FINANCIAL_RESEARCH,
    GENERAL_TASK
}
