package com.apms.domain.assistant.dto;

public enum OwnerIntent {
    ECOSYSTEM_OVERVIEW,
    PARTNERS,
    POTENTIAL_PARTNERS,
    COMPETITORS,
    CUSTOMERS,
    SUPPLIERS,
    COMPANY_RELATIONSHIP,
    RELATIONSHIP_CLOSENESS,
    RISKS,
    OPPORTUNITIES,
    RECENT_SIGNALS,
    OWNER_INSIGHTS,
    COMPANY_PROFILE,
    COMPANY_COMPARE,
    COMPANY_PUBLIC_NEWS,
    STRATEGIC_RECOMMENDATION,
    INTERNAL_NEWS_PROTECTED,
    OUT_OF_SCOPE
}
